### ISSUE TITLE
Depreciated gfunction.uniform_temperature from pygfunction

### ISSUE THREAD

**Issue by wouterpeere** [wouterpeere/GHEtool#12]
Currently, in the function createCustomDataset, the function 'uniform_temperature' from pygfunction is used. This will however be depreciated in pygfunction v3.0. This has to be changed to use the pygfunction.gfunction.gFunction class.

**Comment by wouterpeere** [comment]
The new 'equivalent' method in the gFunction class of pygfunction based on Prieto and Cimmino (2021), is very fast.
Currently, within GHEtool, when you want to size a field, for which the size is not precalculated, a whole new dataset is generated. This is very slow and, now, unnecessary.

This will be changed so, whenever a (rectangular) field is chosen, for which no precalculated data is available, a warning will be thrown and the gfunctions will be calculated immediately.

**Comment by wouterpeere** [comment]
Implementation started in separate branch

**Comment by blcools** [comment]
Hello Wouter. I seem to be having a bug when the dataset is being generated. I did a simulation with a 2x1 field and asked the GHEtool to calculate the necessary depth. When the boreholes are 8,9m apart, the precalculated databases is used and the depth is as expected (about 130m for a family home). When I then tell ask the software to put the boreholes at 10m apart, the dataset is being genereated, but the calulated depth is aproximately half of this 130m.

**Comment by wouterpeere** [comment]
@blcools we will continu this discussion in a separate [issue](https://github.com/wouterpeere/GHEtool/issues/29).

**Comment by wouterpeere** [comment]
Partly implemented, but first tests show an increase in calculation time (for fields which already have precalculated data) of more than a factor of 10.
Ideally, it will be partly JIT, partly precalculated g-function data.

**Comment by wouterpeere** [comment]
For the GUI however, to decrease the setup.exe-file, it can be useful to implement just the JIT g-function calculation and let a separate calculation thread precalculate the required g-function datafiles. So we don't need the 200MB of precalculated data ...
