### ISSUE TITLE
Figure gets bigger and bigger

### ISSUE THREAD

**Issue by wouterpeere** [wouterpeere/GHEtool#131]
When using the optimise load functionality with multiple scenario's, switching back and forth from one result page to the next, increases the size of the temperature plot.

Perhaps this is due to the fact that the optimise load functionality has two plots on the result page, where only the first one shows this behavior.

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I can not reproduce this bug. Can you check if updating python and its packages works and if not please send me your python version?

With best regards
@tblanke

**Comment by tblanke** [comment]
I am running on version 3.10.11 and can not reproduce this error. Can you check if this bug also appears in the gui restuctruing branch?

**Comment by wouterpeere** [comment]
Hi @tblanke 

This does indeed not occur in the gui-restructuring branch, so I will close this issue!

I noticed that scrolling on the result page does not work when hovering over a plot. This was a problem we had before. Perhaps this still needs solving in the issue45-branch?

Beste,
Wouter
