### ISSUE TITLE
Add the possiblity to start in other months then January (like September)

### ISSUE THREAD

**Issue by tblanke** [wouterpeere/GHEtool#140]
Hi @wouterpeere ,

A nice new feature would be the ability to start the simulation not in January but in other months like September.

With best regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

Indeed! I think this would be rather easy to implement once the load classes are finished (since this is just changing the order of the loads). I will already make a branch for this.

Best,
Wouter
