### ISSUE TITLE
Bug when opening scenarios which have autosave enabled

### ISSUE THREAD

**Issue by wouterpeere** [wouterpeere/GHEtool#141]
(This is related to a comment in issue #45 )

**Overwrite newly loaded data**

You can replicate this bug as follows:

1) delete the backup
2) create a random GHEtool file with certain parameters and two different scenario's. Important: set the autosave option to True.
3) save this file
4) save this file again but under another name
5) change one input of the first scenario in the current file
6) save and open the other one
7) you can see that the change you made in the first document, is visible here as well and that the original data is overwritten .

The solution is to disable the autosaving whilst loading a new document

**Comment by tblanke** [comment]
Hi @wouterpeere 

I have found a solution.

**Comment by wouterpeere** [comment]
Hi @tblanke 

For in the GUI restructuring branch?

**Comment by tblanke** [comment]
Yes, Can you take a look at issue141-bug-opening branch?
not your branch(issue141bug-when-opening...)

**Comment by wouterpeere** [comment]
Perfect, I'll take a look at it right now.
It seems to be a different approach ...

**Comment by wouterpeere** [comment]
Yes, works perfectly and way more elegant than my solution!
Can we perhaps implement a test for this behaviour?

**Comment by tblanke** [comment]
I have implemented a test

**Comment by wouterpeere** [comment]
Hi @tblanke 

I noticed some other bug related to the changing of the scenario's (but I think this is a general problem in ScenarioGUI).
When you have multiple scenario's and you change their position, some scenario's can get overwritten.

To replicate:
1) Delete all backup
2) Create a first scenario
3) Set (e.g.) the borehole depth to 1
4) repeat 2 and 3 until you have 5 scenario's with borehole depths 1 to 5
5) drag scenerio 3 to the place of scenario 2
6) notice that scenario 4 has now the depth of scenario 2

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I can not reproduce this behaviour either in GHEtool nor in ScenarioGUI. Can you check if you have the newest Scenario GUI version?

**Comment by wouterpeere** [comment]
Hi @tblanke 

I can create this behaviour in ScenarioGUI itself. But it seems like where I drag it matters.
Perhaps this works for you:

1. Delete all backup
2. Create a first scenario
3. Set (e.g.) the borehole depth to 1
4. repeat 2 and 3 until you have 5 scenario's with borehole depths 1 to 5
5. **drag scenerio 2 to the place of scenario 3**
6. notice that scenario 4 has now the depth of scenario 2

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I have solved the issue in ScenarioGUI. So with the new version this should be fixed.

**Comment by wouterpeere** [comment]
@tblanke let's finish our discussion there, for I found some other problems ... I'll close this thread.
