### ISSUE TITLE
Zoom box is not working in GHEtool v2.2.0

### ISSUE THREAD

**Issue by wouterpeere** [wouterpeere/GHEtool#191]
On the result page of GHEtool, the controls of the figure do not work properly.
This is related to https://github.com/tblanke/ScenarioGUI/issues/164 but it goes further within GHEtool. The zoombox, which is working within ScenarioGUI itself, does not seem to be working within GHEtool.

**Comment by tblanke** [comment]
With matplotlib version 3.7.2 this function works. So I think this is an matplotlib issue.

**Comment by wouterpeere** [comment]
Hi @tblanke 

I think this indeed a problem of matplotlib ...


Best,
@wouterpeere
