### ISSUE TITLE
smaller simulation periods did not work

### ISSUE THREAD

**Issue by tblanke** [wouterpeere/GHEtool#2]
here the error message:
File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\interpolate\interpolate.py", line 2675, in interpn
    raise ValueError("There are %d points and %d values in "
ValueError: There are 74 points and 76 values in dimension 3

**Comment by wouterpeere** [comment]
Solved in commit: 4d3bd6f09023d91b2b272ad8864bda2789d37f24
