### ISSUE TITLE
Shank spacing documentation U-Tube

### ISSUE THREAD

**Issue by p-klebo** [wouterpeere/GHEtool#207]
Hey, 

when setting up a U-Tube, the **documentation** in _DoubleUTube.py_ (or _SingleUTube.py_) is unclear to me.
What does this mean? :
        _D_s : float
            Distance of the pipe until center [m]_

I assume, that here the so-called **shank spacing** has to be entered.
This could be described as the distance between in- and outlet pipe, measured from center to center.
Is this meant by _Distance of the pipe until center [m]_? Entering only the distance from the pipe center to the borehole center leads to results that seem wrong to me.

 
Many thanks in advance,
Paul

**Comment by wouterpeere** [comment]
Dear @p-klebo ,

D_s is exactly that: the distance from one pipe until the center, so its half of the shank spacing as you defined it.

What are the results that seem wrong to you?


Best,
Wouter

**Comment by p-klebo** [comment]
Dear @wouterpeere,

thanks for the response! I have set up the Example 4 from the [EED-Tutorials](https://buildingphysics.com/download/exampleseed.pdf) in the GHETool. If I enter the shank spacing in D_s, GHETool gives a depth of 127 m (EED-Example is 120 m).
If I set D_s = half the shank spacing, GHETool gives 195 m.

I also compared GHETool to the GHEDesigner for some scenarios. It results in the same picture. The results do match for D_s = shank spacing quite well.
Not for D_s = half the shank spacing, in this case GHETool obviously suggest much deeper depths.

Best,
Paul

**Comment by wouterpeere** [comment]
Dear @p-klebo 

Can you perhaps attach the GHEtool document you created. I think something is wrong in your values ...

I entered all the values for the Rb* and I get 0.0741 mK/W (idem EED, see page 20 of the pdf document), when using half the shank spacing.

![image](https://github.com/wouterpeere/GHEtool/assets/52632307/541ac528-6f06-40a6-939e-d434b0419637)

For using EED data for GHEtool projects, you can read this article on the topic: https://manual.ghetool.eu/en/latest/sources/tutorial/EED_to_GHEtool.html

**Comment by p-klebo** [comment]
Hey @wouterpeere,

many thanks for the response and the screenshot! It helped me to find, that my mass flow value was wrong!
Now, I get the same Rb* as in the EED-Tutorials. Btw, I've made a typing error, I have set up Example 5, not Example 4. But that doesn't matter...

Best regards, Paul

**Comment by wouterpeere** [comment]
Hey @p-klebo !

Glad you found your problem!

I'll close this issue now!

Best,
@wouterpeere
