### ISSUE TITLE
Add validation based on Ahmadfard & Bernier

### ISSUE THREAD

**Issue by wouterpeere** [wouterpeere/GHEtool#243]
- [x] Check test_1a
- [x] Check test_1b
- [x] Check test_2
- [x] Check test_3
- [x] Check test_4
- [x] Sensitivity test_4
- [x] Update tests
- [x] Update validation page on RTD

**Comment by wouterpeere** [comment]
@LoneMeertens I have made everything compatible with the newest version of GHEtool and I added some asserts to the documents as well. I noticed that both the sensitivity of test 4 and the different sizes of test 3 are not yet implemented. Do you have that somewhere already?

Best,
Wouter

**Comment by LoneMeertens** [comment]
@wouterpeere I'll update my test 3 file to display all the different sizes. I haven't done the sensitivity analysis for test 4 yet, but I'll implement the code for it today and include the analysis of the different tests in the documentation (https://docs.ghetool.eu/en/latest/sources/code/validation.html).

**Comment by wouterpeere** [comment]
@LoneMeertens 
Any progress on the documentation?

**Comment by LoneMeertens** [comment]
Yes, I have worked on the documentation offline and will finalize it soon. While writing this documentation, I wondered if there could be an additional uncertainty regarding the modification of the constraints for the maximum fluid temperature. Currently, the delta T is calculated based on the maximum peak load. The two uncertainties that came to mind are:

1) Does the maximum/minimum temperature always occur during peak load? In scenarios where the peak load is isolated, this doesn't seem to be the case.
2) The same delta T is used for both the upper and lower constraints. Shouldn't we consider two different delta T values, one for the maximum cooling peak and another for the maximum heating peak?

**Comment by wouterpeere** [comment]
@LoneMeertens 

1. This is only the case in L2 methodologies, in L3/L4 the temperatures are calculated for every month, regardless of its peak power.
2. I do not understand what you mean by 'delta T'. Do you mean: 'the difference between the fluid threshold and the ground temperature'? In that case, can you point to the exact lines where you think there is a mistake? Normally size_L2/L3/L4 does this.

**Comment by LoneMeertens** [comment]
@wouterpeere 

For *testa1a.py* (analogous for other tests), I am referring to lines 44-48 for both questions:

1. When the peak temperature does not occur during the peak power hour, sizing with L3/L4 will still size based on a temperature limit constraint that is transformed based on peak power. Aren't the upper/lower fluid temperature limits therefore too high/low in this case?
2. The formula `delta_t = max(load.max_peak_cooling, load.max_peak_cooling) * 1000 / (fluid_data.Cp * fluid_data.mfr)` is currently used to modify the temperature constraints. The same delta_t is applied to both the upper and lower limits. The upper limit is constrained based on the building's cooling demand, while the lower limit is constrained based on the heating demand. Shouldn't two different delta T values be applied to the lower and upper limits on the fluid temperature respectively?

**Comment by wouterpeere** [comment]
Hi @LoneMeertens , I see. I thought you were talking about main methodologies.

1. You're right. This will lead to more critical temperature limits (peak power will give highest delta T and hence more critical limits). It can be that this give rise to an oversizing, although I think the effect would be minimal. To solve this, we would need a methodology in GHEtool to size for inlet/outlet temperature, so it can be mass flow dependent.
2. Also right. You can indeed change that, although I do not think this will make a big difference as well, but it is more accurate for sure ...

**Comment by LoneMeertens** [comment]
@wouterpeere I will run the different tests with the changes discussed in item 2 and report back here.

**Comment by LoneMeertens** [comment]
@wouterpeere, I've updated the validation page on RTD. Please inform me if further clarification is required or if we can proceed to close this issue.
