### ISSUE TITLE
Custom README for PyPi

### ISSUE THREAD

**Issue by wouterpeere** [wouterpeere/GHEtool#27]
It can be usefull to create a custom README for PyPi since the links currently do not work.

**Comment by tblanke** [comment]
Hi,

You can also use absolute links and not relative onces in the REDME like:
https://github.com/wouterpeere/GHEtool/blob/main/GHEtool/Examples/main_functionalities.py
instead of 
GHEtool/Examples/main_functionalities.py

**Comment by wouterpeere** [comment]
This has been implemented!
