### ISSUE TITLE
Bug spacing

### ISSUE THREAD

**Issue by wouterpeere** [wouterpeere/GHEtool#29]
Hello Wouter. I seem to be having a bug when the dataset is being generated. I did a simulation with a 2x1 field and asked the GHEtool to calculate the necessary depth. When the boreholes are 8,9m apart, the precalculated databases is used and the depth is as expected (about 130m for a family home). When I then ask the software to put the boreholes at 10m apart, the dataset is being genereated, but the calulated depth is aproximately half of this 130m. I might be doing something wrong, but the onlyt thing I did was copy the first scenario and change the distance between the boreholes. The first scenario (with the precalculated data) als fits with what Smartgeotherm calculates, so that looks fine. Might it be that with the newley generated dataset, the calculated length per well is afterwards divided by the total number of boreholes? Kind regard, and thanks for making this software

_Originally posted by @blcools in https://github.com/wouterpeere/GHEtool/issues/12#issuecomment-1262913070_

**Comment by wouterpeere** [comment]
Hi @blcools. Thanks for reporting this bug. I have a couple of questions:
1) Are you using the graphical user interface? It is possible that the bug is related to that, we are working on a new one (see #17)
2) Is it possible to screenshot your heating/cooling load and ground/borehole/fluid parameters so I can try to recreate the bug. You can post the screenshots in this issue.

Thanks in advance!

**Comment by blcools** [comment]
Hi Wouter.

I am using the graphical interface as you suspected. I also have the most
recent Anaconda installed on my PC, which uses Python 3.9 instead of 3.8. I
don't know if this might cause the problem.
I have made some screenshots. I have put them in attachment of this e-mail.

Kind regards.


Op vr 7 okt. 2022 om 14:25 schreef Wouter Peere ***@***.***>:

**Comment by wouterpeere** [comment]
Hi @blcools 

I think this is one of the bugs in the current beta-version of the GUI. When I run it in the codebase, switching from a 9m spacing to 9.5m spacing, decreases the required depth, but only slightly (as one would expect). (GHEtool is compatible with python 3.8, 3.9 and 3.10, so your python version cannot cause any issue)

We are currently working on the new GUI, so this problem should be solved in the new version of the software.

If you have further questions, feel free to contact me by email (wouter.peere@kuleuven.be). I will couple this issue to the issue related to the new GUI.

**Comment by blcools** [comment]
Thanks for the update!

Op ma 10 okt. 2022 12:39 schreef Wouter Peere ***@***.***>:
