### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by honeypottt** [wouterpeere/GHEtool#39]
When running the program twice from the gui (win 10), I get a permission error: 
`PermissionError: [Errno 13] Permission denied: 'backup.pkl'`

1. install GHEtool gui (win 10)
2. run GHetool gui
3. click on 'Calculate current scenario' -> results shown fine
4. click on 'Calculate current scenario' again (no additional actions) -> crash, application closes (see screenshot in attachment)
<img width="660" alt="XhvR4A22IE" src="https://user-images.githubusercontent.com/28269810/195268709-ad1cb66f-e23f-4422-b39f-09d2ee88d6a7.png">

**Comment by tblanke** [comment]
Hi [honeypottt](https://github.com/honeypottt),

We are working on this issue. It should be fixed in the new GUI version. For now you can try to run the programm in admin mode.

With best regards
[tblanke](https://github.com/tblanke)

**Comment by honeypottt** [comment]
> Hi [honeypottt](https://github.com/honeypottt),
> 
> We are working on this issue. It should be fixed in the new GUI version. For now you can try to run the programm in admin mode.
> 
> With best regards [tblanke](https://github.com/tblanke)

Can confirm admin mode works. Thanks

**Comment by wouterpeere** [comment]
Should be fixed in the new gui, already available in branch v2.1.0, which is going to be released soon.
