### ISSUE TITLE
Restructure package

### ISSUE THREAD

**Issue by wouterpeere** [wouterpeere/GHEtool#45]
Currently, all the functionalities of GHEtool are placed in the main_class.py, with a few variable classes.

Since the number of functionalities of GHEtool is increasing, a new structure is needed in order to cope with this changes.
This issue is related to this task.

The idea is to split the main_class.py into a Borefield, GeothermalSystem and HybridGeothermalSystem class, each extending on the previous class.

- The Borefield class will contain all the information about borefield sizing from the borefield perspective itself.
- The GeothermalSystem class takes the heat pumps into account, so there can be accounted for variable COP's. Also the functionality to optimise the load profile will be moved to this class, since it works with the geothermal system and not so much the borefield itself. The active- and passive cooling functionality will be implemented here.
- The HybridGeothermalSystem class will move towards a hybridisation of the system. E.g. regeneration will be taken into account here.

Furthermore, up until now, everything related to g-functions has been part of the main_class.py. This will also be moved to a seperate class to improve readability.

**Comment by wouterpeere** [comment]
Everything related to the g-function calculation is moved to issue #57 .

**Comment by wouterpeere** [comment]
- [ ] _calculate_temperature_profile should be changed once optimise_load_profile is moved into the GeothermalSystem class. Currently, it checks whether or not 'hourly_heating_load_on_the_borefield' differs from an empty array. When using the GeothermalSystem class, all the profiles in the Borefield class will be geothermal by nature, so this distinction is no longer needed! The _calculate_temperature_profile which will be implemented into the GeothermalSystem class will use only the 'load_on_the_borefield' to calculate everything.

**Comment by wouterpeere** [comment]
For this major restructuring, the following tasks will be created in separate subbranches (issue45-restructure-package-XX). Afterwards all these branches will be merged into the issue45-restructure-package branch and merged into the main branch.
The goal of this restructuring is creating classes which have single responsibilities.

- [ ] GUI: restructure gui so calculation thread and data storage class don't need to be altered anymore.
- [ ] GUI: split gui_classes into seperate classes in a new folder
- [ ] Grounddata: create ground data metaclass with three instances: GroundConstantTemperature, GroundFluxTemperature, GroundGradientTemperature. This will make the 'use_constant_Tg' variable in SizingSetup class obsolete
- [ ] Load: create a meta class for the loads with two subclasses (monthly and hourly). These separate classes make it so that the check whether or not there is hourly load available, becomes obsolete, due to the difference in classes themselves.
- [ ] Limit: create an abstract class for the temperature limits, with two subclasses: ConstantTemperatureLimit and VariableTemperatureLimit. These classes also contain the simultion_period data
- [ ] Pipe: create an abstract pipe class with two subclasses: UPipe and CoaxialPipe. This also refers to issue #40 .
- [ ] Borehole: create a borehole class, containing a pipe class, fluid class and the Rb* calculation. Also the param 'use_constant_Rb' can be moved in this class.

**Comment by wouterpeere** [comment]
After all the above changes are implemented, we have to look at two things:

- [ ] Backwards compatibility (we need to update this test to include v2.1.2).
- [ ] The JSON storage for I do not know if it is capable right now of storing nested classes. This has to be checked later.

**Comment by wouterpeere** [comment]
- [ ] Update documentation

**Comment by tblanke** [comment]
Hi @wouterpeere,

I have implemented a new json apporach which should take care of the different types of objects for the Ground Data etc. The main think we have to take care of is to define the v2.1.1 Version of the different object. Like GroundFluxTemperature is the groundData type for v2.1.1. Important is that the Object can handle all possible data like the flux attribute for the groundData, which the GroundConstantTemperature does not have. Can you please have a look at it?

With best regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

I noticed some bugs when loading files in the GUI restructuring branch.
You can replicate this bug as follows:
1) delete the backup
2) create a random GHEtool file with certain parameters and two different scenario's. Important: set the autosave option to True.
3) save this file
4) save this file again but under another name
5) change one input of the first scenario in the current file
6) save and open the other one
7) you can see that the change you made in the first document, is visible here as well

Best,
@wouterpeere

**Comment by wouterpeere** [comment]
Hi @tblanke 

I noticed you created a max_depth function in issue45-restructure-package-load, like this: "(t_max - self.Tg)/(2 * self.flux) * 2 * self.flux". This does not return a depth buth a temperature, as far as I can tell, since the '2*self.flux' cancel out.

**Comment by tblanke** [comment]
Hi @wouterpeere ,

Correct I have uploaded a fix. It is (t_max - self.Tg)/self.flux * self.k_s

**Comment by wouterpeere** [comment]
Hi @tblanke 

I added the coaxial pipes to the GUI (branch issue45-restructure-package-pipe).
Can you just add the German translations for the last 6 rows in the translations.csv document?
Afterwards is will merge this into the main issue45-restructure-package branch.


Best regards,
@wouterpeere

**Comment by tblanke** [comment]
Hi @wouterpeere,

done.

With best regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

Thanks!
I was implementing tests for the coaxial pipe in the gui, when I noticed that the equivalent borehole thermal resistance of the coaxial pipe (in contrast with the U-tubes) does not depend on the ground thermal conductivity. I opened an issue on pygfunction to check this: https://github.com/MassimoCimmino/pygfunction/issues/263

Do you think this is normal behaviour?

Best,
@wouterpeere
