### ISSUE TITLE
Temperature gradient is wrong by factor 2

### ISSUE THREAD

**Issue by tblanke** [wouterpeere/GHEtool#64]
Hi @wouterpeere 

The temperature gradient in the gui of for example 3 K/100 m is leading to an average ground temperature of 13 °C if a 10 °C ground temperature is selected. I think this should be 11.5 °C.
I have created a new branch for this. So if  i am right you can just create a pull request.

With best regards 
@tblanke

**Comment by wouterpeere** [comment]
This is indeed a bug. Thanks for noticing!
I updated the CHANGELOG and documentation and will proceed with the PR.
