### ISSUE TITLE
Change the default value for the simulation period to 50 years

### ISSUE THREAD

**Issue by tblanke** [wouterpeere/GHEtool#65]
Hi @wouterpeere ,

I have heard from people in Germany that we normally run simulations for 50 years. We need this as well for applications. What do you think about this? Do you need 20 years in Belgium?

With best regards
@tblanke

**Comment by wouterpeere** [comment]
In Belgium, this depends. Practitioners often use 20/25 years for investment exercises, but from a sustainability point of view, we often follow the 40 years as suggested by BREEAM. Is it fine if we meet at 40 years, instead of the current 20?

**Comment by tblanke** [comment]
Yes
