### ISSUE TITLE
Sometimes the wrong options are shown

### ISSUE THREAD

**Issue by tblanke** [wouterpeere/GHEtool#75]
Hi @wouterpeere,

Sometimes the wrong options are shown for the selected options. This issue seems to be fixed by show and hide the linked options if the main options is shown/hidden.

With best regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke, thanks for noticing this. Can you elaborate on how you can repoduce this error?
I will take a closer look at it, in the beginning of January!

Best regards,
Wouter

**Comment by tblanke** [comment]
First delete the backup.
Then select determine borehole depth and the L4 sizing method
Then select determine temperature profile
And no peak length is displayed.

**Comment by wouterpeere** [comment]
@tblanke, indeed, I noticed this also. However, when you selected L4 sizing, you most likely also loaded an hourly profile. Then, when switching to 'determine temperature profile' the hourly profile still is loaded, making the 'peak length' option obsolete.

**Comment by wouterpeere** [comment]
@tblanke, while working on #61 it seems like this is a more logical behavior. I will open the PR.
