### ISSUE TITLE
Move scenario functionality is not working

### ISSUE THREAD

**Issue by wouterpeere** [wouterpeere/GHEtool#80]
Normally, it should be possible to drag and drop scenarios in the scenario list to change their position. This functionality was already implemented, but it doesn't seem like it is working.

**Comment by wouterpeere** [comment]
Solution has been implemented. It seems like just one line is missing.
@tblanke , can you please check if this functionality works for you?

**Comment by tblanke** [comment]
Hi @wouterpeere ,

 have reopened the issue branch to create a pytest for the changing of a scenario. If you are fine with the test you can create a pull request to merge it into the main.

with best regards
@tblanke

**Comment by wouterpeere** [comment]
Looks perfect, I will create the PR!
