### ISSUE TITLE
Large file size when storing GHEtool projects

### ISSUE THREAD

**Issue by wouterpeere** [wouterpeere/GHEtool#81]
When you have, for example, 10 scenario's calculated, saving them would require 60mB of data (due to the fact that also all the borefield objects are stored in a JSON-format). On the other hand, discarding the borefield objects and just storing the values within the gui itself, only requires 31kB.

For sharing purposes, it can be beneficial to only send the minimum amount of information (in the example above 31kB) instead of the whole, 60mB version.

It can be a good idea to implement two features:

- [x] store borefield objects: yes/no
- [x] next to 'save project', implement a button for 'export project', where the borefield objects are not storedµ

In a next step:
- [x] investigate if we can store only part of the borefield object data

**Comment by wouterpeere** [comment]
Therefore, an 'export borefield' icon should be created.

**Comment by tblanke** [comment]
A third option could be to reduce the borefield saved data. Due to the fact, that the main time is needed to calculate the g-function. An option could be to just store this variable and calculate the rest of borefield variables.

**Comment by wouterpeere** [comment]
Hi @tblanke ,

That is indeed a good idea. For now, I already removed the time_L4 variable and made it a property. This already excludes an enormous amount of data (100kb/scenario instead of 6mB), and hences solves already a lot of such storage problems.

However, when working with hourly data, the problem is even worse for it stores (for a simulation period of 20 years) not only 8760*20 values for heating/cooling load, but also that much in g-function data. We can investigate that further.

**Comment by tblanke** [comment]
The returned pygfunction g-function is normally pretty small < 10 values. And the calculated values can be recalculated again, so just 8760 values from the external file have to be stored, I think.

**Comment by wouterpeere** [comment]
This issue is solved in v2.2.0, together with the backwards compatibility issues.
