### ISSUE TITLE
Exe-Update

### ISSUE THREAD

**Issue by tblanke** [wouterpeere/GHEtool#83]
Hi @wouterpeere ,

I have implemented new features for the installed GUI version:
1.	Stored files (*.GHEtool) can be loaded by double click
2.	Reduced the exe-file size from > 135 to about 60 MB, by setting up a fresh virtual environment with just the needed packages and using a pyinstaller folder instead of a file.
3.	Updated explanation for the docs (w.r.t. 2.)
4.	Added setup.cfg to the pyinstaller folder because it was missing
5. Exe can be installed either locally for one user without admin permission or for all users using admin permission

Can you please check if it also works from your side?
With best regards

@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

This sounds like a great addition! I will check it asap, most likely this weekend.

Best regards
Wouter
