### ISSUE TITLE
Rename scenario did not work

### ISSUE THREAD

**Issue by tblanke** [wouterpeere/GHEtool#86]
Hi @wouterpeere ,

The renaming scenario function did not work. I have already fixed it and created a new branch. Furthermore, I have created a lot more tests for the GUI in this branch. The main thing missing are the error handling in the thread class.

With best regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

Thanks for noticing this and solving the issue. I will continue with the PR.
