### ISSUE TITLE
Sizing (L2, L3, L4) with no heating or cooling load does not work

### ISSUE THREAD

**Issue by tblanke** [wouterpeere/GHEtool#91]
Hi @wouterpeere ,

The borefield depth sizing with L2, L3 and L4 raises an ValueError that the depth is below zero. This just happens if either no heating or no cooling load is needed. This happens because by sizing in quadrant 1 or quadrant 3 there are no loads so no depth can be determined.

I have implemented three different solutions:
I have created a Custom Error (SmallerThenZeroError) to catch this specific error. 
So L2 sizing can catch this error and deal with this (set H to zero). 
For L3 sizing I catch this in the sizing method and return zero if the size gets below 0.
L4 not even size by this quadrants. So it checks if there are no heating or cooling loads then skip the corresponding quadrant.

@wouterpeere: What are your thought`s?

I am going to upload these in the correspinding branch.

With best regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

Thanks for pointing this out. Your solution looks fine to me. I will go over it in more detail later this week.

Best,
@wouterpeere
