### ISSUE TITLE
Add a logger to the GUI

### ISSUE THREAD

**Issue by wouterpeere** [wouterpeere/GHEtool#96]
This issue is related to the creation of a log file for the GHEtool GUI.

**Comment by tblanke** [comment]
Hi @wouterpeere 

I have made the last changes from my side. Can you add the error messages in the Main class?

With Best regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

Is it possible that the documentation is no longer up to date with the multithreading?
Also, currently, I believe due to this multithreading, a lot of logs are like this:
"2023-02-18 15:27:37 - root - INFO - [] (gui_combine_window.py:1131)", which is not that useful ...

Another change you made is that in gui_structure, now everything refers to the translation class, which I believe is great. Perhaps we should implement a test somewhere to check if for all the slots in the translation class, the lists are the same size (meaning all the labels have the same number of translations). 

I will implement the logging of error messages in the main class.

Best,
@wouterpeere

**Comment by wouterpeere** [comment]
Hi @tblanke 

When playing around with the gui, I think the multithreading is somehow causing some weird behavior, which I cannot fully explain for now. Can we open a separate issue for this and remove the multithreading from this issue?

Best,
Wouter

**Comment by wouterpeere** [comment]
There are also two minor things I noticed about the GUI:
- a line next to 'Progress:' it would be nicer if this was gone
![image](https://user-images.githubusercontent.com/52632307/219884368-7cf959f2-bd0f-49f6-a54e-15b14000e53e.png)
- calculations buttons remain high when status bar has gone due to the log message. This is rather strange. I would set the log message on the right of the scenario list, on the same level as the buttons (instead of at the same place where the progress bar was before).
![image](https://user-images.githubusercontent.com/52632307/219884421-44086c05-7967-4888-9801-304971cc2e9f.png)

**Comment by tblanke** [comment]
Yes a small single issue can be sensefull. I will take a look on friday.

**Comment by tblanke** [comment]
> remove the multithreading from this issue?

Yes we should create the own one.

**Comment by tblanke** [comment]
Hi @wouterpeere ,

I have created a test for the translation length.
Progress bar and status bar has been changed, as mentioned above.
The empty message has been deleted.
Can you specifiy the "somehow causing some weird behavior" in the new issue in more detail?
For now the optional is disabled in the Logger branch.

With best regards
@tblanke

**Comment by wouterpeere** [comment]
Hi @tblanke 

I brought the logger up to date with the main branch to start working on log messages in the main_class.py.
I noticed that the status bar was not exactly where I thought it should be: 
![image](https://user-images.githubusercontent.com/52632307/222117384-55a02f70-7393-4744-b719-41376de74d44.png)
In my opinion, it is better that this is on the same line as the calculation buttons.

Best regards
@wouterpeere
