### ISSUE TITLE
Add possibility to create ground data with layers

### ISSUE THREAD

**Issue by tblanke** [wouterpeere/GHEtool#97]
It would be nice to have ground data with different layer where each has their own conductivity and heat capacity. 

TODO:
- [x] Create ground classes so multiple layers can be set
- [x] Adapt sizing methods to work with multiple layers
- [x] Adapt temperature plotting to work with multiple layers
- [x] Write documentation
- [x] Write tests

**Comment by wouterpeere** [comment]
- [ ] Create ground classes so multiple layers can be set
- [ ] Adapt sizing methods to work with multiple layers
- [ ] Adapt temperature plotting to work with multiple layers
- [ ] Adapt GUI so multiple layers can be inputted
- [ ] Write documentation
- [ ] Write tests
